server:
  port: 5000
  context-path: /uaa

spring:
  application:
    name: sc-security-auth-server
  datasource:
    url: jdbc:mysql://mysql.host:3306/DB_SC_Security_OAuth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/