eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 5000
management: 
  security: 
    enabled: false 
logging: 
  file: "logs/boot-admin-sample.log"
## spring 配置  
spring:
  application:
    name: sc-monitor-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
 
    