server:
  port: 8672
## 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
## Spring 配置
spring:
  application:
    name: sc-security-auth-resource-service-hi
  datasource:
    url: jdbc:mysql://mysql.host:3306/DB_SC_Security_OAuth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: service-hi
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server














