eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 9600
## spring 配置  
spring:
  application:
    name: sc-zipkin-server-mysql
  datasource:
    url: jdbc:mysql://mysql.host:3306/DB_SC_Zipkin?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

   
## 
zipkin: 
  storage: 
    type: mysql
    
    
    