eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 5000
  
spring:
  application:
    name: sc-zipkin-gateway-service
  sleuth: 
    sampler: 
      percentage: 1.0 
  zipkin: 
    base-url: http://localhost:9600 
zuul: 
  routes: 
   api-a:  
     path: /user-api/**
     serviceId: sc-zipkin-user-service
     
     

    
    
    