eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 8769
management: 
  security: 
    enabled: false 
logging: 
  file: "logs/sc-monitor-turbine-service.log"
## spring 配置  
spring:
  application:
    name: sc-monitor-turbine-service
    
## turbine 配置
turbine: 
  aggregator: 
    clusterConfig: default 
  appConfig: sc-monitor-turbine-client,sc-monitor-turbine-client-two
  clusterNameExpression: new String("default")
  
 