eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 9600
  
spring:
  application:
    name: sc-zipkin-mq-server
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
     
     

    
    
    