eureka:
  client:
    serviceUrl:
    # defaultZone 为默认的 Zone，来源于 AWS 的概念 .
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的注册地址
server:
  port: 8763
management: 
  security: 
    enabled: false 
logging: 
  file: "logs/sc-monitor-turbine-client-two.log"
## spring 配置  
spring:
  application:
    name: sc-monitor-turbine-client-two
 